import Foundation
import SwiftUI

// MARK: - Localization Service

final class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    @Published var currentLang: String = {
        let preferred = Locale.preferredLanguages.first ?? "zh-CN"
        if preferred.hasPrefix("zh") { return "zh-CN" }
        if preferred.hasPrefix("ko") { return "ko" }
        if preferred.hasPrefix("ja") { return "ja" }
        return "en"
    }()

    private let allStrings: [String: [String: String]] = [
        "zh-CN": [
            "presets": "选择光效",
            "preset_hint": "预设",
            "shutter_hint": "拍照",
            "timer_hint": "定时",
            "screen_brightness": "屏幕亮度",
            "color_brightness": "颜色亮度",
            "select_light": "选择光效",
            "built_in": "内置光效",
            "my_presets": "我的光效",
            "custom": "自定义",
            "custom_hint": "创建自定义光效",
            "long_press_hint": "长按编辑或删除",
            "unsaved_hint": "选取颜色",
            "choose_action": "选择操作",
            "edit": "编辑",
            "delete": "删除",
            "cancel": "取消",
            "custom_color": "自定义颜色",
            "solid": "纯色",
            "gradient": "渐变",
            "split": "双色",
            "start": "起点",
            "end": "终点",
            "angle": "角度",
            "split_position": "分隔",
            "quick_select": "快速选择",
            "save_as_preset": "保存为光效",
            "use_once": "仅使用一次",
            "rename_title": "请为这个光效起个名字",
            "rename_placeholder": "我的光效",
            "rename_confirm": "保存",
            "save_success": "光效已保存！",
            "update_success": "光效已更新！",
            "preset_sakura": "樱花微醺粉",
            "preset_golden": "黄金时刻奶黄",
            "preset_aurora": "极光紫薰衣草",
            "preset_coral": "珊瑚礁蜜桃",
            "preset_glacier": "冰川蓝冰白",
            "preset_matcha": "抹茶雾浅绿",
            "preset_smoke": "烟灰银珍珠白",
            "preset_deepsea": "深海夜光深蓝",
            "settings": "设置",
            "language": "语言 / Language",
            "feedback": "反馈",
            "haptic_feedback": "震动反馈",
            "about": "关于",
            "version": "版本",
            "rate_us": "给我们评分",
            "contact": "联系我们",
            "mirror": "镜像",
            "mirror_on": "镜像：开",
            "mirror_off": "镜像：关",
            "timer_2s": "2秒",
            "timer_5s": "5秒",
            "timer_10s": "10秒",
            "burst": "三连拍",
            "burst_captured": "三连拍完成！",
            "photo_saved": "照片已保存到相册",
            "share": "分享",
            "dismiss": "关闭",
            "onboarding_title_1": "欢迎使用补光相机",
            "onboarding_body_1": "用屏幕作为专业补光板\n暗光环境也能拍出完美自拍",
            "onboarding_title_2": "场景化光效",
            "onboarding_body_2": "10种预设光效一键切换\n从日落咖啡馆到清晨薄荷",
            "onboarding_title_3": "自定义颜色",
            "onboarding_body_3": "色轮选择器自由调色\n创建你的专属光效方案",
            "onboarding_next": "下一步",
            "onboarding_start": "开始拍摄",
            "onboarding_skip": "跳过",
            "revert_to_current": "恢复当前",
        ],
        "en": [
            "presets": "Light Effects",
            "preset_hint": "Preset",
            "shutter_hint": "Capture",
            "timer_hint": "Timer",
            "screen_brightness": "Screen Brightness",
            "color_brightness": "Color Brightness",
            "select_light": "Light Effects",
            "built_in": "Built-in",
            "my_presets": "My Presets",
            "custom": "Custom",
            "custom_hint": "Create Custom Effect",
            "long_press_hint": "Long press to edit or delete",
            "unsaved_hint": "Pick a color",
            "choose_action": "Choose Action",
            "edit": "Edit",
            "delete": "Delete",
            "cancel": "Cancel",
            "custom_color": "Custom Color",
            "solid": "Solid",
            "gradient": "Gradient",
            "split": "Split",
            "start": "Start",
            "end": "End",
            "angle": "Angle",
            "split_position": "Split",
            "quick_select": "Quick Select",
            "save_as_preset": "Save Effect",
            "use_once": "Use Once",
            "rename_title": "Name this light effect",
            "rename_placeholder": "My Effect",
            "rename_confirm": "Save",
            "save_success": "Effect saved!",
            "update_success": "Effect updated!",
            "preset_sakura": "Sakura Rosy Pink",
            "preset_golden": "Golden Hour Cream",
            "preset_aurora": "Aurora Deep Purple",
            "preset_coral": "Coral Reef Peach",
            "preset_glacier": "Glacier Ice Blue",
            "preset_matcha": "Matcha Mist Green",
            "preset_smoke": "Smoke Silver Pearl",
            "preset_deepsea": "Deep Sea Glow Blue",
            "settings": "Settings",
            "language": "Language",
            "feedback": "Feedback",
            "haptic_feedback": "Haptic Feedback",
            "about": "About",
            "version": "Version",
            "rate_us": "Rate Us",
            "contact": "Contact Us",
            "mirror": "Mirror",
            "mirror_on": "Mirror: On",
            "mirror_off": "Mirror: Off",
            "timer_2s": "2 sec",
            "timer_5s": "5 sec",
            "timer_10s": "10 sec",
            "burst": "Burst",
            "burst_captured": "Burst captured!",
            "photo_saved": "Photo saved to library",
            "share": "Share",
            "dismiss": "Dismiss",
            "onboarding_title_1": "Welcome to LightCam",
            "onboarding_body_1": "Turn your screen into a pro fill light\nPerfect selfies even in low light",
            "onboarding_title_2": "Scene Presets",
            "onboarding_body_2": "10 presets, one-tap switch\nFrom Sunset Cafe to Morning Mint",
            "onboarding_title_3": "Custom Colors",
            "onboarding_body_3": "Color wheel for freeform picking\nCreate your signature light effect",
            "onboarding_next": "Next",
            "onboarding_start": "Start Shooting",
            "onboarding_skip": "Skip",
            "revert_to_current": "Revert to Current",
        ],
        "ko": [
            "presets": "조명 효과",
            "preset_hint": "프리셋",
            "shutter_hint": "촬영",
            "timer_hint": "타이머",
            "screen_brightness": "화면 밝기",
            "color_brightness": "색상 밝기",
            "select_light": "조명 효과",
            "built_in": "내장 효과",
            "my_presets": "내 효과",
            "custom": "사용자 정의",
            "custom_hint": "사용자 정의 효과 생성",
            "long_press_hint": "길게 눌러 편집 또는 삭제",
            "unsaved_hint": "색상 선택",
            "choose_action": "작업 선택",
            "edit": "편집",
            "delete": "삭제",
            "cancel": "취소",
            "custom_color": "사용자 정의 색상",
            "solid": "단색",
            "gradient": "그라데이션",
            "split": "분할",
            "start": "시작",
            "end": "끝",
            "angle": "각도",
            "split_position": "분할",
            "quick_select": "빠른 선택",
            "save_as_preset": "효과 저장",
            "use_once": "한 번만 사용",
            "rename_title": "조명 효과 이름 지정",
            "rename_placeholder": "내 효과",
            "rename_confirm": "저장",
            "save_success": "효과가 저장되었습니다!",
            "update_success": "효과가 업데이트되었습니다!",
            "preset_sakura": "사쿠라 로즈 핑크",
            "preset_golden": "골든 아워 크림",
            "preset_aurora": "오로라 딥 퍼플",
            "preset_coral": "코럴 리프 피치",
            "preset_glacier": "글레이셔 아이스 블루",
            "preset_matcha": "말차 미스트 그린",
            "preset_smoke": "스모크 실버 펄",
            "preset_deepsea": "딥씨 글로우 블루",
            "settings": "설정",
            "language": "언어",
            "feedback": "피드백",
            "haptic_feedback": "햅틱 피드백",
            "about": "정보",
            "version": "버전",
            "rate_us": "평가하기",
            "contact": "문의하기",
            "mirror": "미러",
            "mirror_on": "미러: 켜짐",
            "mirror_off": "미러: 꺼짐",
            "timer_2s": "2초",
            "timer_5s": "5초",
            "timer_10s": "10초",
            "burst": "연속촬영",
            "burst_captured": "연속촬영 완료!",
            "photo_saved": "사진이 저장되었습니다",
            "share": "공유",
            "dismiss": "닫기",
            "onboarding_title_1": "LightCam에 오신 것을 환영합니다",
            "onboarding_body_1": "화면을 전문 조명으로 바꾸세요\n어두운 곳에서도 완벽한 셀카",
            "onboarding_title_2": "장면 프리셋",
            "onboarding_body_2": "10가지 프리셋 원터치 전환\n일몰 카페부터 모닝 민트까지",
            "onboarding_title_3": "사용자 정의 색상",
            "onboarding_body_3": "컬러휠로 자유롭게 색상 선택\n나만의 조명 효과 만들기",
            "onboarding_next": "다음",
            "onboarding_start": "촬영 시작",
            "onboarding_skip": "건너뛰기",
            "revert_to_current": "현재로 복원",
        ],
        "ja": [
            "presets": "ライト効果",
            "preset_hint": "プリセット",
            "shutter_hint": "撮影",
            "timer_hint": "タイマー",
            "screen_brightness": "画面の明るさ",
            "color_brightness": "色の明るさ",
            "select_light": "ライト効果",
            "built_in": "ビルトイン",
            "my_presets": "マイプリセット",
            "custom": "カスタム",
            "custom_hint": "カスタム効果を作成",
            "long_press_hint": "長押しで編集または削除",
            "unsaved_hint": "色を選択",
            "choose_action": "操作を選択",
            "edit": "編集",
            "delete": "削除",
            "cancel": "キャンセル",
            "custom_color": "カスタムカラー",
            "solid": "単色",
            "gradient": "グラデーション",
            "split": "分割",
            "start": "始点",
            "end": "終点",
            "angle": "角度",
            "split_position": "分割",
            "quick_select": "クイック選択",
            "save_as_preset": "効果を保存",
            "use_once": "一度だけ使用",
            "rename_title": "ライト効果の名前を入力",
            "rename_placeholder": "マイ効果",
            "rename_confirm": "保存",
            "save_success": "効果を保存しました！",
            "update_success": "効果を更新しました！",
            "preset_sakura": "桜のほろ酔いピンク",
            "preset_golden": "ゴールデンアワークリーム",
            "preset_aurora": "オーロラディープパープル",
            "preset_coral": "コーラルリーフピーチ",
            "preset_glacier": "グレイシャーアイスブルー",
            "preset_matcha": "抹茶ミストグリーン",
            "preset_smoke": "スモークシルバーパール",
            "preset_deepsea": "ディープシーグローブルー",
            "settings": "設定",
            "language": "言語",
            "feedback": "フィードバック",
            "haptic_feedback": "触覚フィードバック",
            "about": "情報",
            "version": "バージョン",
            "rate_us": "評価する",
            "contact": "お問い合わせ",
            "mirror": "ミラー",
            "mirror_on": "ミラー: オン",
            "mirror_off": "ミラー: オフ",
            "timer_2s": "2秒",
            "timer_5s": "5秒",
            "timer_10s": "10秒",
            "burst": "連写",
            "burst_captured": "連写完了！",
            "photo_saved": "写真を保存しました",
            "share": "共有",
            "dismiss": "閉じる",
            "onboarding_title_1": "LightCamへようこそ",
            "onboarding_body_1": "画面をプロの照明に変える\n暗い場所でも完璧な自撮り",
            "onboarding_title_2": "シーンプリセット",
            "onboarding_body_2": "10種類のプリセットをワンタップで切替\nサンセットカフェからモーニングミントまで",
            "onboarding_title_3": "カスタムカラー",
            "onboarding_body_3": "カラーホイールで自由に色を選択\nあなた専用のライト効果を作成",
            "onboarding_next": "次へ",
            "onboarding_start": "撮影を始める",
            "onboarding_skip": "スキップ",
            "revert_to_current": "現在に戻す",
        ],
    ]

    private init() {}

    func localized(_ key: String) -> String {
        allStrings[currentLang]?[key] ?? allStrings["en"]?[key] ?? key
    }

    func localized(_ key: String, for lang: String) -> String {
        allStrings[lang]?[key] ?? allStrings["en"]?[key] ?? key
    }

    var availableLanguages: [(code: String, displayName: String)] {
        [
            ("zh-CN", "简体中文"),
            ("en", "English"),
            ("ko", "한국어"),
            ("ja", "日本語"),
        ]
    }
}
